### ISSUE TITLE
Support all message types in jlkernel

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/IJulia.jl#4]
Currently, we only (barely) support `execute_request` and the corresponding replies.  We need to support all of the [IPython message types](http://ipython.org/ipython-doc/dev/development/messaging.html):
- [x] `execute_request` and `execute_reply` (incomplete, see #5)
- [x] `pyout`
- [ ] `getattr_request` and `getattr_reply` / `setattr_request` and `setattr_reply` (these may not actually be part of the spec as per @minrk's comment below)
- [x] `object_info_request` and `object_info_reply`
- [x] `complete_request` and `complete_reply`
- [ ] `history_request` and `history_reply` (needed in qtconsole front-end).  Stub implementation (commit f1da940b3ab899fee36d4750c442bca1c66027de) pending clarification in ipython/ipython#3806.
- [x] `connect_request` and `connect_reply`
- [x] `kernel_info_request` and `kernel_info_reply`
- [x] `shutdown_request` and `shutdown_reply`
- [x] `stream` (need stdout/stderr redirection from [Julia #3823](https://github.com/JuliaLang/julia/issues/3823))
- [x] `display_data` (depends on JuliaLang/julia#3817)
- [ ] `data_pub`
- [x] `pyin`
- [x] `pyerr` (may require protocol updates with IPython folks)
- [x] `status`
- [x] ~~`crash`~~ (not actually in the spec, see below)
- [ ] `input_request` / `input_reply` (stdin redirection) #42
